/glg4debug/glg4param omit_muon_processes  0.0
/glg4debug/glg4param omit_hadronic_processes  0.0

/rat/db/set DETECTOR experiment "jsns2"
/rat/db/set DETECTOR geo_file "jsns2/jsns2.geo"
/rat/db/set MC thin_factor 1.5

/run/initialize

/process/inactivate Cerenkov

/tracking/storeParticleTrajectory e+
/tracking/storeParticleTrajectory e-
/tracking/storeParticleTrajectory gamma
/tracking/storeParticleTrajectory neutron
/tracking/storeParticleTrajectory deutreron
/tracking/storeParticleTrajectory Gd156
/tracking/storeParticleTrajectory Gd158
/tracking/storeParticleTrajectory C12


#/glg4scint/off

/rat/proc jsnsdaq
/rat/procset trigger_mode 0

/rat/proc count
/rat/procset update 1

/rat/proclast outroot


/generator/add external external:poisson:"/home/mlf/zayunsna/official_work/generator/JSNS2_eventGenerator_pack/thermal_n/externalVer/ext_gamma_gen/JSNS2_ANNRI_Gd/dat/ext_gamma_NumT.dat"

/run/beamOn 200
#/run/beamOn 1
